// Every field of the CRC-P Round 19 application form, in document order.
//
// anchor:      exact text (trimmed) of the question's paragraph in the government DOCX.
// answerAfter: exact text of the last paragraph of the question block; the answer box
//              goes after it. Defaults to the anchor. [text, n] = the n-th paragraph with
//              that text from the anchor on.
// Both are searched from the previous field's position onwards, so repeated texts
// ("Given name", "Yes/No") resolve to the right occurrence. build.mjs records the
// occurrence and paragraph ordinal it found; check.mjs verifies them.
//
// kind (spec 05 §3): narrative (drafted) · data (filled from sources) · confirm (the
// advisor fills; never pre-filled or suggested) · budget (out of scope in v1) · rule
// (checked by code). The question text is copied from the DOCX by build.mjs.
//
// repeat: the portal asks the block once per partner / person / milestone / site.

export const fields = [
  { id: 'AF-A.1', label: 'Program selection', kind: 'data',
    anchor: 'You must select from a drop-down menu the program that you are applying for. If you have been provided with an Invitation code, you will be able to enter it here which will select the program for you.',
    answerAfter: 'Field 1 select - Cooperative Research Centres Projects Round 19',
    fixedValue: 'Cooperative Research Centres Projects Round 19' },

  // Eligibility
  { id: 'AF-B.1', label: 'SME at lodgement', kind: 'confirm', input: 'yes-no',
    anchor: 'Are you a SME at lodgement of this application?', answerAfter: 'You must answer yes to proceed to next question.' },
  { id: 'AF-B.2', label: 'Registered for GST', kind: 'confirm', input: 'yes-no',
    anchor: 'Are you registered for the Goods and Services Tax (GST)?', answerAfter: 'You must answer yes to proceed to next question' },
  { id: 'AF-B.3', label: 'Entity type', kind: 'confirm', input: 'yes-no',
    anchor: 'Are you one of the following:', answerAfter: 'You must answer yes to proceed to next question.' },
  { id: 'AF-B.4', label: 'Minimum project partners', kind: 'confirm', input: 'yes-no',
    anchor: 'Will your CRC Project include amongst its project partners at least:', answerAfter: 'You must answer yes to proceed to next question.' },
  { id: 'AF-B.5', label: 'Grant up to 50% of eligible expenditure', kind: 'confirm', input: 'yes-no',
    anchor: 'Is the grant amount requested up to 50 percent of total eligible project expenditure?', answerAfter: 'You must answer yes to proceed to next question.' },
  { id: 'AF-B.6', label: 'At least $200,000 eligible project value', kind: 'confirm', input: 'yes-no',
    anchor: 'Does your project have at least $200,000 in total eligible project value?', answerAfter: 'You must answer yes to proceed to next section.' },

  // Applicant address and contacts
  { id: 'AF-C.1', label: 'Applicant street address', kind: 'data', input: 'address',
    anchor: 'Applicant street address', answerAfter: 'When you start typing the address in the field you can select the correct one from the drop down list that appears. If it is not there you can enter manually.' },
  { id: 'AF-C.2', label: 'Applicant postal address', kind: 'data', input: 'address',
    anchor: 'Applicant postal address', answerAfter: 'When you start typing the address in the field you can select the correct one from the drop down list that appears. If it is not there you can enter manually.' },
  { id: 'AF-D.1', label: 'Primary contact', kind: 'data',
    anchor: 'Primary contact', answerAfter: 'Relationship to applicant',
    parts: ['Title (optional)', 'Given name', 'Family name', 'Phone number', 'Email address', 'Relationship to applicant'] },
  { id: 'AF-D.2', label: 'Authorised signatory', kind: 'data',
    anchor: 'Authorised signatory', answerAfter: 'Email address',
    parts: ['Title (optional)', 'Given name', 'Family name', 'Phone number', 'Email address'] },

  // About your organisation
  { id: 'AF-E.1', label: 'Latest financial year figures', kind: 'data', input: 'whole-numbers',
    anchor: 'Has your organisation existed for a complete financial year?',
    answerAfter: 'Number of individuals engaged by your organisation under a commercial contract (rather than an employment contract) to provide employee-like services on site.',
    parts: ['Existed for a complete financial year', 'Latest financial year completed', 'Months completed in the financial year to date', 'Sales revenue (turnover)', 'Export revenue', 'R&D expenditure', 'Taxable income', 'Number of employees including working proprietors and salaried directors (headcount)', 'Number of independent contractors (headcount)'] },
  { id: 'AF-E.2', label: 'ANZSIC code', kind: 'data', input: 'dropdown',
    anchor: 'Provide the Australian and New Zealand Standard Industrial Classification (ANZSIC) details for your organisation from a drop-down menu:',
    answerAfter: 'your organisation’s main revenue earning ANZSIC class.',
    parts: ['ANZSIC division', 'ANZSIC class'] },
  { id: 'AF-E.3.1', label: 'Indigenous owned', kind: 'confirm', input: 'yes-no',
    anchor: 'Is your organisation Indigenous owned?',
    answerAfter: 'An organisation is considered Indigenous owned where at least 51% of the organisation’s members or proprietors are Indigenous.' },
  { id: 'AF-E.3.2', label: 'Indigenous controlled', kind: 'confirm', input: 'yes-no',
    anchor: 'Is your organisation Indigenous controlled?',
    answerAfter: 'An organisation is considered Indigenous controlled where at least 51% of the organisation’s board or management committee is Indigenous.' },

  // Project partners (asked once per partner, lead included)
  { id: 'AF-F.1', label: 'Partner ABN and entity name', kind: 'data', repeat: 'partner',
    anchor: 'Legal or Registered Entity Name',
    answerAfter: 'Entity name refers to the name that appears on all official documents or legal papers. The entity name may be different from the business name.',
    parts: ['ABN', 'Legal or registered entity name'] },
  { id: 'AF-F.2', label: 'Partner contributions', kind: 'budget', repeat: 'partner',
    anchor: 'Project partner contributions',
    answerAfter: 'As all partners must contribute resources to the CRC-P, you should not select \'No\'. If you have $0 contributions for a particular field, you still need to enter a 0, otherwise you get an error message alerting that no value has been entered.' },
  { id: 'AF-F.3', label: 'Financial workbook', kind: 'budget',
    anchor: 'CRC Project Application Financial workbook',
    answerAfter: 'The template can be downloaded from the key documents listing at business.gov.au.' },
  { id: 'AF-F.4a', label: 'Partner details', kind: 'data', repeat: 'partner',
    anchor: 'Partner Details', answerAfter: 'Partner type (large industry, SME, research organisation or other)',
    parts: ['Organisation name', 'ABN details', 'Authorised representative name', 'Position', 'Business address', 'Postal address', 'Phone', 'Email', 'Partner type (large industry, SME, research organisation or other)'] },
  { id: 'AF-F.4b', label: 'Partner involvement', kind: 'narrative', repeat: 'partner',
    anchor: 'Partner’s involvement in the CRC-P.',
    answerAfter: 'describe the partner\'s role and involvement in the CRC-P, and how the partner will provide their contributions.',
    shareGroup: 'AF-F.4' },
  { id: 'AF-F.4c', label: 'Partner structure and relationships', kind: 'narrative', repeat: 'partner',
    anchor: 'describe the project partner’s company structure and relationships with the other project partners (This may include related entities, entities with the same ultimate holding company, entities with common directorship, entities with common major shareholders.).',
    answerAfter: 'Your partner involvement response is limited to 1000 characters including spaces and does not support formatting.',
    shareGroup: 'AF-F.4' },
  { id: 'AF-F.4d.1', label: 'Partner Indigenous owned', kind: 'confirm', input: 'yes-no', repeat: 'partner',
    anchor: 'Is the project partner Indigenous owned?',
    answerAfter: 'An organisation is considered Indigenous owned where at least 51% of the organisation’s members or proprietors are Indigenous.' },
  { id: 'AF-F.4d.2', label: 'Partner Indigenous controlled', kind: 'confirm', input: 'yes-no', repeat: 'partner',
    anchor: 'Is the project partner Indigenous controlled? An organisation is considered Indigenous controlled where at least 51% of the organisations’ board or management committee is Indigenous.' },
  { id: 'AF-F.4e', label: 'Partner confirmations', kind: 'confirm', input: 'checkbox', repeat: 'partner',
    anchor: 'In regards to this project partner:',
    answerAfter: 'By checking this box I can confirm the authorised representative of this partner is aware of and agrees to the above statements.' },

  // Project information
  { id: 'AF-G.1a', label: 'Project title', kind: 'narrative', charLimit: 75,
    anchor: 'Provide a project title.',
    answerAfter: 'Your response is limited to 75 characters including spaces and does not support formatting.' },
  { id: 'AF-G.1b', label: 'Brief project description', kind: 'narrative', charLimit: 750,
    anchor: 'Provide a brief project description for publication.',
    answerAfter: 'Ensure your project description focuses on your project’s key activities and outcomes. Outline what it is you are going to do and how these activities will benefit your organisation.' },
  { id: 'AF-G.2', label: 'Detailed project description and key activities', kind: 'narrative', charLimit: 5000,
    anchor: 'Provide a detailed description of your project and key activities.',
    answerAfter: 'Describe in detail what your project involves, including the project scope, what activities are involved and how are you going to implement them?' },
  { id: 'AF-G.3', label: 'Project outcomes', kind: 'narrative', charLimit: 5000,
    anchor: 'Provide a summary of the expected project outcomes.',
    answerAfter: 'What result do you anticipate in undertaking this project? Explain how this will help your organisation, referencing the objectives of the grant opportunity.' },
  { id: 'AF-G.4', label: 'Key personnel', kind: 'data', repeat: 'person', repeatMax: 3,
    anchor: 'Provide details of up to 3 key personnel working on the project. For example, include the staff leading the project and key researchers involved. This reflects the individual’s position in the project, for example project manager, project coordinator, research leader, researcher.',
    answerAfter: 'Your response to the project role is limited to 75 characters including spaces and does not support formatting.',
    parts: [{ label: 'Title' }, { label: 'Name' }, { label: 'Organisation' }, { label: 'Position' }, { label: 'Project role', charLimit: 75 }] },
  { id: 'AF-G.5', label: 'Industry context', kind: 'narrative', charLimit: 2000,
    anchor: 'What is the national and international state of play in the research area that is contributing to solve the identified industry problem or opportunity?',
    answerAfter: 'Provide a description of the research landscape relating to the identified industry problem and how this relates to or complements your proposed project.' },
  { id: 'AF-G.6.1', label: 'Starting TRL', kind: 'data', input: 'number',
    anchor: 'What is the estimated TRL for your project at the commencement date?', answerAfter: 'Enter number' },
  { id: 'AF-G.6.2', label: 'Target TRL', kind: 'data', input: 'number',
    anchor: 'What is the expected TRL for your project at the completion date?', answerAfter: 'Enter number' },
  { id: 'AF-G.7.1', label: 'Working with Indigenous communities', kind: 'data', input: 'yes-no',
    anchor: 'Does your project involve working with Indigenous communities?', answerAfter: 'Yes or No.' },
  { id: 'AF-G.7.2', label: 'How the project works with Indigenous communities', kind: 'narrative', charLimit: 2000,
    condition: { field: 'AF-G.7.1', equals: 'Yes' },
    anchor: 'If yes describe how this will be carried out (for example, research, consultation, use of Traditional and Cultural Knowledge)',
    answerAfter: 'Your response is limited to 2000 characters including spaces and does not support formatting' },
  { id: 'AF-G.8', label: 'Project duration', kind: 'data',
    anchor: 'Project duration', answerAfter: 'Estimated project duration (in months)',
    parts: ['Estimated project start date', 'Estimated project end date', 'Estimated project duration (in months)'] },
  { id: 'AF-G.9', label: 'Project milestones', kind: 'narrative', repeat: 'milestone', repeatMin: 3, repeatMax: 10,
    anchor: 'Provide measurable milestones you will reach while undertaking your project. You must add between 3 and 10 milestones.',
    answerAfter: 'Estimated end date',
    parts: [{ label: 'Milestone title', charLimit: 100 }, { label: 'Milestone description', charLimit: 750 }, { label: 'Estimated start date', kind: 'data' }, { label: 'Estimated end date', kind: 'data' }] },
  { id: 'AF-G.10', label: 'Project location', kind: 'data', repeat: 'site',
    anchor: 'You must provide the address where your project will be undertaken and the estimated percentage of project value expected to be undertaken at that site. If you have multiple sites you must add the address of each site.',
    answerAfter: 'Estimated percentage of project value expected to be undertaken at site',
    parts: ['Project site address', 'Estimated percentage of project value expected to be undertaken at site'] },
  { id: 'AF-G.11.1', label: 'Pecuniary penalties', kind: 'confirm', input: 'yes-no',
    anchor: 'Have any of your board members, management or persons of authority been subject to any pecuniary penalty?',
    answerAfter: 'A pecuniary penalty is a monetary penalty that can be civil, criminal or administrative, imposed by a Commonwealth, state, or territory court or entity.' },
  { id: 'AF-G.11.2', label: 'Pecuniary penalty details', kind: 'confirm', charLimit: 750,
    condition: { field: 'AF-G.11.1', equals: 'Yes' },
    anchor: 'If yes, provide details of the penalty.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-G.12a.1', label: 'Foreign support to the project', kind: 'confirm', input: 'yes-no',
    anchor: 'Does your project receive any funding or non-financial support from a foreign source?' },
  { id: 'AF-G.12a.2', label: 'Foreign support details', kind: 'confirm', charLimit: 750,
    condition: { field: 'AF-G.12a.1', equals: 'Yes' },
    anchor: 'If yes, provide details of the foreign financial support.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-G.12b.1', label: 'Foreign support to entities or personnel', kind: 'confirm', input: 'yes-no',
    anchor: 'Do any entities or key personnel involved with the project receive financial support or benefits from a foreign source?' },
  { id: 'AF-G.12b.2', label: 'Foreign support arrangement details', kind: 'confirm', charLimit: 750,
    condition: { field: 'AF-G.12b.1', equals: 'Yes' },
    anchor: 'If yes, provide details of the arrangement.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-G.12c.1', label: 'Foreign talent program', kind: 'confirm', input: 'yes-no',
    anchor: 'Do any entities or key personnel involved with the project have any current or former association with a foreign talent program?' },
  { id: 'AF-G.12c.2', label: 'Foreign talent program details', kind: 'confirm', charLimit: 750,
    condition: { field: 'AF-G.12c.1', equals: 'Yes' },
    anchor: 'If yes, provide details of the foreign talent program.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-G.12d.1', label: 'Foreign government, military or SOE ties', kind: 'confirm', input: 'yes-no',
    anchor: 'Do any entities or key personnel involved with the project have any ties to a foreign government, military or state-owned enterprise?' },
  { id: 'AF-G.12d.2', label: 'Foreign ties details', kind: 'confirm', charLimit: 750,
    condition: { field: 'AF-G.12d.1', equals: 'Yes' },
    anchor: 'If yes, provide details of the affiliations or associations.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-G.13', label: 'National security plan', kind: 'confirm', input: 'yes-no',
    anchor: 'Do you have a plan to manage any potential security risks associated with the project and your organisation more broadly?',
    answerAfter: 'The plan should include protecting your organisation from potential national security risks including cyber security threats and the secure handling of data. We may ask for a copy of your plan at a later stage.' },

  // Project budget (out of scope in v1)
  { id: 'AF-H.1', label: 'Eligible expenditure', kind: 'budget',
    anchor: 'Provide a summary of your eligible project expenditure over the life of the project.',
    answerAfter: 'You are strongly advised to use the CRC Project Application Financial Workbook provided at business.gov.au It will assist you in calculating the correct  funds and contributions required for your budget.' },
  { id: 'AF-H.1.2', label: 'Other eligible expenditure details', kind: 'budget', charLimit: 750,
    anchor: 'Details of ‘Other’ eligible expenditure.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-H.1.3', label: 'In-kind eligible expenditure details', kind: 'budget', charLimit: 750,
    anchor: 'Details of ‘In-kind’ eligible expenditure.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-H.2', label: 'Grant amount sought', kind: 'budget',
    anchor: 'Enter grant amount sought $',
    answerAfter: 'The grant amount can be up to 50% of the total eligible project expenditure.' },

  // Assessment criteria
  ...[1, 2, 3, 4].map((n) => ({
    id: `AF-I.${n}`, label: `Assessment criterion ${n}`, kind: 'narrative', charLimit: 5000,
    shareGroup: `AF-I.${n}`,
    anchor: `Assessment criterion ${n} (25 points)`,
    answerAfter: {
      1: 'how your project will encourage and facilitate SME participation (7 points).',
      2: 'the education and training opportunities your project will provide to build capability and capacity in the industry and research sectors for example include the number of students the project will impact (7 points).',
      3: 'your access to required resources including naming personnel with the right skills and experience, funding, security, infrastructure, technology and intellectual property (10 points).',
      4: 'the commercial potential of your project, including the expected commercial outputs such as new products, processes or services, any expected spill over benefits and plans at the end of the project (9 points).',
    }[n],
  })),

  // Government priorities
  { id: 'AF-J.1.1', label: 'Develops or enhances AI', kind: 'data', input: 'yes-no',
    anchor: 'Does your CRC-P develop or enhance AI systems and technologies, to help accelerate the development and commercialisation of AI by businesses and researchers across Australia?',
    answerAfter: 'Yes/No' },
  { id: 'AF-J.1.2', label: 'How the project meets the AI criterion', kind: 'narrative', charLimit: 500,
    condition: { field: 'AF-J.1.1', equals: 'Yes' },
    anchor: 'If yes, explain how your project meets this criterion.',
    answerAfter: 'Your response is limited to 500 characters including spaces and does not support formatting.' },
  { id: 'AF-J.2', label: 'National Reconstruction Fund priority areas', kind: 'data', input: 'dropdown',
    anchor: 'Indicate the priority areas of the National Reconstruction Fund the CRC-P will contribute to.',
    answerAfter: ['Enter priority', 2],
    parts: ['Primary alignment', 'Secondary alignment'] },
  { id: 'AF-J.3', label: 'National Science and Research Priorities', kind: 'data', input: 'dropdown',
    anchor: 'Indicate the priority areas of the Science and Research Priorities the CRC-P will contribute to.',
    answerAfter: ['Enter priority', 2],
    parts: ['Primary alignment', 'Secondary alignment'] },
  { id: 'AF-J.4', label: 'First Nations organisation', kind: 'confirm', input: 'yes-no',
    anchor: 'Are you an Aboriginal and Torres Strait Islander organisation with an Indigenous Corporation Number (ICN) or Supply Nation registered?',
    answerAfter: 'If yes, upload evidence.' },
  { id: 'AF-J.5', label: 'Other government priorities', kind: 'narrative', repeat: 'priority', repeatMax: 3,
    anchor: 'There may be other government priorities that the CRC Project addresses. List up to three of these below.',
    answerAfter: ['Your response is limited to 300 characters including spaces and does not support formatting.', 2],
    parts: [{ label: 'Government priority', charLimit: 300 }, { label: 'Basis for government priority (report, statement, etc.)', charLimit: 300 }] },
  { id: 'AF-J.6.1', label: 'Other government assistance', kind: 'confirm', input: 'yes-no',
    anchor: 'Have any of the project partners received any Commonwealth, state and/or territory government assistance during the past five years that has assisted in the development of this project?',
    answerAfter: 'Yes or No response' },
  { id: 'AF-J.6.2', label: 'Government assistance details', kind: 'data', repeat: 'assistance',
    condition: { field: 'AF-J.6.1', equals: 'Yes' },
    anchor: 'Assistance Source (Agency and Program)', answerAfter: 'details',
    parts: [{ label: 'Assistance Source (Agency and Program)', charLimit: 500 }, { label: 'start date' }, { label: 'end date' }, { label: 'amount' }, { label: 'details' }] },
  { id: 'AF-J.6.3', label: 'Results of government assistance', kind: 'narrative', charLimit: 500,
    condition: { field: 'AF-J.6.1', equals: 'Yes' },
    anchor: 'Discuss the results of any government assistance received in the last five years, specifically what the assistance was used for, what results were achieved and how this has contributed to the proposed project.',
    answerAfter: 'Your response is limited to 500 characters including spaces and does not support formatting.' },
  { id: 'AF-J.7', label: 'Intellectual property category', kind: 'data', input: 'dropdown',
    anchor: 'If the project depends on access to protected IP, select the relevant category:',
    answerAfter: 'Not applicable to project.',
    options: ['Applicant developed and owns IP', 'Applicant has licensed IP from a third party', 'Third party will license or assign IP to the applicant', 'Not applicable to project.'] },

  // Bank account
  { id: 'AF-K.1', label: 'Bank account details', kind: 'data',
    anchor: 'Account details', answerAfter: 'Account number',
    parts: ['Account name', 'BSB', 'Account number'] },
  { id: 'AF-K.2', label: 'Payment contact', kind: 'data',
    anchor: 'Payment contact', answerAfter: 'Phone number',
    parts: ['Title (optional)', 'Given name', 'Family name', 'Email address', 'Phone number'] },

  // Application finalisation
  { id: 'AF-L.1.1', label: 'Conflicts of interest', kind: 'confirm', input: 'yes-no',
    anchor: 'Do you have any perceived or existing conflicts of interest to declare?',
    answerAfter: 'Refer to the grant opportunity guidelines for further information on your conflict of interest responsibilities.' },
  { id: 'AF-L.1.2', label: 'Conflict of interest description', kind: 'confirm', charLimit: 750,
    condition: { field: 'AF-L.1.1', equals: 'Yes' },
    anchor: 'If yes, describe the perceived or existing conflicts of interest.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-L.1.3', label: 'Conflict of interest management', kind: 'confirm', charLimit: 750,
    condition: { field: 'AF-L.1.1', equals: 'Yes' },
    anchor: 'If yes, describe how you anticipate managing this conflict.',
    answerAfter: 'Your response is limited to 750 characters including spaces and does not support formatting.' },
  { id: 'AF-L.2', label: 'Attachments', kind: 'confirm', input: 'upload',
    anchor: 'Attach additional supporting documentation here. You should only attach documents that we have requested (where applicable).',
    answerAfter: 'Where you have indicated your entity type is a trustee applying on behalf of a trust, you must attach trust documents showing the relationship of the incorporated trustee to the trust.' },
  { id: 'AF-L.3', label: 'Program feedback', kind: 'confirm',
    anchor: 'How did you hear about this grant opportunity?',
    answerAfter: ['Your response is limited to 750 characters including spaces and does not support formatting.', 2],
    parts: [{ label: 'How did you hear about this grant opportunity?' }, { label: 'Did you read the grant opportunity guidelines?' }, { label: 'If yes, how useful were the guidelines in completing your application?' }, { label: 'We welcome any additional feedback on the guidelines.', charLimit: 750 }, { label: 'How satisfied were you with the process of applying for this grant?' }, { label: 'We welcome any additional feedback on the application process', charLimit: 750 }] },

  // Declaration
  { id: 'AF-M.1', label: 'Privacy and confidentiality', kind: 'confirm', input: 'checkbox',
    anchor: 'I acknowledge that this is an Australian Government program and that the Department of Industry, Science and Resources (the department) will use the information I provide in accordance with the following:',
    answerAfter: 'The department will publish information on individual grants in the public domain, including on the department’s website, unless otherwise prohibited by law.' },
  { id: 'AF-M.2', label: 'Applicant declaration', kind: 'confirm', input: 'checkbox',
    anchor: 'I declare that I have read and understood the grant opportunity guidelines, including the grant agreement, privacy, confidentiality and disclosure provisions.',
    answerAfter: 'By checking this box I agree to all of the above declarations and confirm all of the above statements to be true.' },
];
